function [pars_not_to_sens] = load_pars_not_to_sens()
 pars_not_to_sens = {'type_of_input', ...
 'dt', ...
 'MRO2_poly_0', ...
 'MRO2_poly_1', ...
 'MRO2_poly_2', ...
 'MRO2_poly_3', ...
 'MRO2_poly_4', ...
 'MRO2_poly_5', ...
 'MRO2_poly_6', ...
 'MRO2_poly_7', ...
 'MRO2_poly_8', ...
 'MRCO2_poly_0', ...
 'MRCO2_poly_1', ...
 'MRCO2_poly_2',...
 'MRCO2_poly_3', ...
 'MRCO2_poly_4',...
 'MRCO2_poly_5',...
 'MRCO2_poly_6', ...
 'MRCO2_poly_7', ...
 'MRCO2_poly_8', ...
 'fiO2_poly_0', ...
 'fiO2_poly_1', ...
 'fiO2_poly_2', ...
 'fiO2_poly_3',...
 'fiO2_poly_4',...
 'tau', ...
 'MRCO2', ...
 'MRO2', ...
 'TE', ... 
 'TI', ... 
 'Tresp', ...
 'a0', ... 
 'a1', ...
 'a2', ...
 'fO2', ...
 'settling_time', ...
 't0', ...
 'Ta', ...
 'V_unstressed_s_v', ...
 'V_unstressed_rm_v', ...
 'MO2_p', ...
 'V_unstressed_sa', ... 
 'R_pp', ...
 'Wp_h_s', ...
 'Pabdmax', ...
 'gcc_v_s', ...
 'Pao', ...
 'V_unstressed_pa', ...
 'bua', ...
 'V_vc_min', ...
 'D2', ...
 'K2_vc', ...
 'Rl', ...
 'Theta_h_s_n', ...
 'delay_Emax_lv', ...
 'R_am_n' , ... 
 'R_am_p_0' , ...
 'R_b_n' , ...
 'R_e_n' , ...
 'R_e_p_0' , ...
 'R_h_n' , ...
 'R_h_p_n' , ...
 'R_pp' , ...
 'R_pv' , ...
 'R_rm_n' , ...
 'R_rm_p_0' , ...
 'R_s_n' , ...
 'R_s_p_0' , ... 
 'V_u_am_v_0' , ...
 'V_u_e_v_0' , ...
 'V_u_rm_v_0' , ...
 'V_u_s_v_0' , ...
 'V_unstressed_am_p' , ...
 'V_unstressed_am_v' , ...
 'V_unstressed_b_p' , ...
 'V_unstressed_b_v' , ...
 'V_unstressed_e_p' , ...
 'V_unstressed_e_v' , ...
 'V_unstressed_h_p' , ...
 'V_unstressed_h_v' , ...
 'V_unstressed_pp' , ...
 'V_unstressed_pv' , ...
 'V_unstressed_rm_p' , ... 
 'V_unstressed_s_p' , ...
 'V_unstressed_vc',...
 'MRtCO2_basal'};

end
